### ISSUE TITLE
Failed to start CRI Interface for Docker Application Container Engine

### ISSUE THREAD

**Issue by UniKylin** [Mirantis/cri-dockerd#247]
## Expected Behavior
Using systemctl start cri-docker.service success.

## Actual Behavior
[root@peter-node system]# systemctl status cri-docker.service
● cri-docker.service - CRI Interface for Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/cri-docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 六 2023-10-07 17:51:31 CST; 15s ago
     Docs: https://docs.mirantis.com
  Process: 3184 ExecStart=/usr/bin/cri-dockerd --container-runtime-endpoint fd:// --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9 (code=exited, status=203/EXEC)
 Main PID: 3184 (code=exited, status=203/EXEC)

10月 07 17:51:29 peter-node systemd[1]: Failed to start CRI Interface for Docker Application Container Engine.
10月 07 17:51:29 peter-node systemd[1]: Unit cri-docker.service entered failed state.
10月 07 17:51:29 peter-node systemd[1]: cri-docker.service failed.
10月 07 17:51:31 peter-node systemd[1]: cri-docker.service holdoff time over, scheduling restart.
10月 07 17:51:31 peter-node systemd[1]: Stopped CRI Interface for Docker Application Container Engine.
10月 07 17:51:31 peter-node systemd[1]: start request repeated too quickly for cri-docker.service
10月 07 17:51:31 peter-node systemd[1]: Failed to start CRI Interface for Docker Application Container Engine.
10月 07 17:51:31 peter-node systemd[1]: Unit cri-docker.service entered failed state.
10月 07 17:51:31 peter-node systemd[1]: cri-docker.service failed.

## Steps to Reproduce the Problem

  1. tar -zxvf cri-dockerd-0.3.2.arm64.tgz
  2. mv cri-dockerd/cri-dockerd /usr/bin/
  3. Config files cri-docker.service & cri-docker.socket
```
[root@peter-node ~]# cat /etc/systemd/system/cri-docker.service
[Unit]
Description=CRI Interface for Docker Application Container Engine
Documentation=https://docs.mirantis.com
After=network-online.target firewalld.service docker.service
Wants=network-online.target
Requires=cri-docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/cri-dockerd --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always

# Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
# Both the old, and new location are accepted by systemd 229 and up, so using the old location
# to make them work for either version of systemd.
StartLimitBurst=3

# Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
# Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
# this option work for either version of systemd.
StartLimitInterval=60s

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Comment TasksMax if your systemd version does not support it.
# Only systemd 226 and above support this option.
TasksMax=infinity
Delegate=yes
KillMode=process

[Install]
WantedBy=multi-user.target
```

```
[root@peter-node ~]# cat /etc/systemd/system/cri-docker.socket
[Unit]
Description=CRI Docker Socket for the API
PartOf=cri-docker.service

[Socket]
ListenStream=%t/cri-dockerd.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```
  4. `systemctl daemon-reload`
  5. `systemctl enable cri-docker`
  6. `systemctl start cri-docker`. Em....occur error in this step.

## Specifications

  - Version: cri-dockerd-0.3.2.arm64.tgz
  - Platform: centos 3.10.0-1160.el7.x86_64
  - Subsystem:

**Comment by UniKylin** [comment]
Fix config file "ExecStart=/usr/bin/cri-dockerd" to "ExecStart=/usr/bin/cri-docker", repeat cli command operations, still have the same errors

**Comment by UniKylin** [comment]
Using `systemctl list-unit-files | grep cri-docker` and cri-docker.service status is enabled. Wondering what went wrong

**Comment by nwneisen** [comment]
Hey @UniKylin, Thanks for reporting the issue. Am I understanding that this is now fixed and working for you?

**Comment by UniKylin** [comment]
Hey @nwneisen I don't think it's fixed yet. I don't even know where the problem is right now. So need your help.

**Comment by neersighted** [comment]
Closing as this is not a cri-dockerd issue; when you see status 203 it means systemd cannot execute your binary; the best way to debug this sort of issue is by running it "manually" from an interactive root shell with the same arguments.

**Comment by UniKylin** [comment]
I found the problem, but thank you for your kind response. @afbjorklund @neersighted

**Comment by 18580543261** [comment]
> I found the problem, but thank you for your kind response. @afbjorklund @neersighted

hello, I have the same error, can i konw how you handle it?

**Comment by afbjorklund** [comment]
Use the rpm or deb for installation, then the package manager will tell you if you are trying to install the binary for the wrong architecture...

**Comment by 18580543261** [comment]
> Use the rpm or deb for installation, then the package manager will tell you if you are trying to install the binary for the wrong architecture...

thank you, i found the solution in 
https://github.com/Mirantis/cri-dockerd/issues/145
